import { ChevronDown, History, RefreshCw, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { resolveFromPath } from "@/lib/utils";

type Port = { port: string; protocol: string; state: string; service: string; product: string; version: string; extra_info: string };
type Host = { address: string; hostname: string; state: string; ports: Port[] };
type Scan = { id: string; created_at_ms: number; target: string; profile: string; executor: string; command: string; duration_ms: number; hosts: Host[] };
type Props = { element: { id: string; from?: string }; store: Record<string, unknown>; onAction?: (action: string, event?: { value?: unknown }) => void };

function portDetails(port: Port) {
  return [port.product, port.version, port.extra_info].filter(Boolean).join(" · ") || "No version detected";
}

export default function NmapHistory({ element, store, onAction }: Props) {
  const data = (resolveFromPath(element.from, { store }) ?? {}) as { message?: string; scans?: Scan[] };
  const scans = data.scans ?? [];
  const remove = (id: string) => onAction?.("nmap.delete_history_entry", { value: { id } });
  return <div id={element.id} className="mx-auto w-full max-w-5xl space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-card p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-primary/10 p-3 text-primary"><History /></div><div><h1 className="text-xl font-semibold">Scan history</h1><p className="text-sm text-muted-foreground">{data.message || "Saved Nmap scans"}</p></div></div><div className="flex gap-2"><Button variant="outline" onClick={() => onAction?.("nmap.refresh_history")}><RefreshCw /> Refresh</Button><Button variant="destructive" disabled={scans.length === 0} onClick={() => onAction?.("nmap.clear_history")}> <Trash2 /> Clear all</Button></div></div>{scans.length === 0 ? <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">No completed scans have been saved yet.</CardContent></Card> : scans.map((scan) => <Card key={scan.id}><CardContent className="py-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono font-medium">{scan.target}</p><p className="mt-1 text-sm text-muted-foreground">{new Date(scan.created_at_ms).toLocaleString()} · {scan.profile} · {scan.executor}</p></div><div className="flex items-center gap-4"><div className="text-right"><p className="font-medium">{scan.hosts.reduce((count, host) => count + host.ports.length, 0)} open ports</p><p className="text-sm text-muted-foreground">{(scan.duration_ms / 1000).toFixed(1)} s</p></div><Button variant="ghost" size="icon" aria-label={`Delete ${scan.target}`} onClick={() => remove(scan.id)}><Trash2 className="text-destructive" /></Button></div></div><details className="mt-4 rounded-lg border bg-muted/20"><summary className="flex cursor-pointer list-none items-center justify-between px-4 py-3 text-sm font-medium">View discovered services <ChevronDown className="size-4 text-muted-foreground" /></summary><div className="space-y-4 border-t p-4"><p className="rounded bg-background p-3 font-mono text-xs text-muted-foreground break-all">{scan.command}</p>{scan.hosts.map((host) => <div key={host.address}><p className="mb-2 text-sm font-medium">{host.address}{host.hostname ? ` · ${host.hostname}` : ""}</p>{host.ports.length === 0 ? <p className="text-sm text-muted-foreground">No open ports.</p> : <div className="overflow-x-auto rounded-md border"><table className="w-full text-sm"><thead className="bg-muted/50 text-left text-muted-foreground"><tr><th className="p-3 font-medium">Port</th><th className="p-3 font-medium">Service</th><th className="p-3 font-medium">Product and version</th></tr></thead><tbody>{host.ports.map((port) => <tr key={`${port.protocol}-${port.port}`} className="border-t"><td className="p-3 font-mono">{port.port}/{port.protocol}</td><td className="p-3">{port.service || "Unknown"}</td><td className="p-3 text-muted-foreground">{portDetails(port)}</td></tr>)}</tbody></table></div>}</div>)}</div></details></CardContent></Card>)}</div>;
}
