[workspace]
members = [
    "daemon/daemon_core",
    "shared/plugin_interface",
    "plugins/plugin_test",
    "plugins/plugin_test_2",
    "plugins/griffon_cleaner",
    "daemon/runner",
    "daemon/plugin_manager",
    "shared/ipc_protocol",
    "gui/src-tauri",
    "cli",
    "shared/logger",
]
resolver = "2"


[workspace.dependencies]
# Shared dependencies across the workspace
plugin_manager = { path = "daemon/plugin_manager" }
plugin_interface = { path = "shared/plugin_interface" }
ipc_protocol = { path = "shared/ipc_protocol" }
logger = { path = "shared/logger" }
abi_stable = "0.11.3"


[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
