# --- STAGE 1: Build du GUI (Vite + Tauri Binary) ---
FROM node:20-slim AS gui-builder
WORKDIR /app
# dep for tauri
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    pkg-config \
    libssl-dev \
    libgtk-3-dev \
    libwebkit2gtk-4.1-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev \
    xdg-utils
# rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

COPY . .
WORKDIR /app/gui
RUN npm install

# build gui
RUN npx tauri build

# --- STAGE 2: Build du workspace Rust (daemon + cli) ---
FROM rust:1.94-slim AS workspace-builder
WORKDIR /app
RUN apt-get update && apt-get install -y pkg-config libssl-dev

COPY . .
RUN cargo build --release --workspace --exclude griffon-gui

# packaging avec nfpm
FROM goreleaser/nfpm:latest AS packager
WORKDIR /app

# Copie des binaires compilés & script de packaging
COPY --from=gui-builder /app/target/release/ /app/target/release/
COPY --from=workspace-builder /app/target/release/ /app/target/release/

COPY nfpm.yaml .
COPY logo.png .
COPY griffon.desktop .
COPY scripts/ ./scripts/

# copy plugin config files
COPY ./plugins/griffon_cleaner/libgriffon_cleaner.toml ./plugins/griffon_cleaner/libgriffon_cleaner.toml
COPY ./plugins/griffon_scanner/libgriffon_scanner.toml ./plugins/griffon_scanner/libgriffon_scanner.toml
COPY daemon/griffon-daemon.service ./daemon/griffon-daemon.service

ENTRYPOINT ["sh", "scripts/build-packages.sh"]
