# --- STAGE 1: Build du GUI (Vite + Tauri Binary) ---
FROM node:20-slim AS gui-builder
WORKDIR /app
# dep for tauri
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    pkg-config \
    libssl-dev \
    libgtk-3-dev \
    libwebkit2gtk-4.1-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev \
    xdg-utils

# rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

COPY . .
WORKDIR /app/gui

# Cache NPM dependencies
RUN --mount=type=cache,target=/root/.npm \
    npm install

# Cache Cargo registry, git, and the target folder (isolated with id=gui-target).
# We use 'find' to only copy the compiled binaries, ignoring the messy deps/ folder.
RUN --mount=type=cache,target=/root/.cargo/registry \
    --mount=type=cache,target=/root/.cargo/git \
    --mount=type=cache,id=gui-target,target=/app/target \
    npx tauri build && \
    mkdir -p /app/gui-out && \
    find /app/target/release -maxdepth 1 -type f -exec cp {} /app/gui-out/ \;


# --- STAGE 2: Build du workspace Rust (daemon + cli) ---
FROM rust:1.94-slim AS workspace-builder
WORKDIR /app
RUN apt-get update && apt-get install -y pkg-config libssl-dev

COPY . .

# Cache Cargo (isolated with id=ws-target).
# We use 'find' to extract only the daemon binary and plugin .so files.
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,id=ws-target,target=/app/target \
    cargo build --release --workspace --exclude griffon-gui && \
    mkdir -p /app/ws-out && \
    find /app/target/release -maxdepth 1 -type f -exec cp {} /app/ws-out/ \;


# --- STAGE 3: packaging avec nfpm ---
FROM goreleaser/nfpm:latest AS packager
WORKDIR /app

# Copie des binaires compilés depuis les dossiers NON-CACHÉS
COPY --from=gui-builder /app/gui-out/ /app/target/release/
COPY --from=workspace-builder /app/ws-out/ /app/target/release/

COPY nfpm.yaml .
COPY logo.png .
COPY griffon.desktop .
COPY scripts/ ./scripts/

# copy plugin config files
COPY ./plugins/griffon_cleaner/libgriffon_cleaner.toml ./plugins/griffon_cleaner/libgriffon_cleaner.toml
COPY ./plugins/griffon_scanner/libgriffon_scanner.toml ./plugins/griffon_scanner/libgriffon_scanner.toml
COPY daemon/griffon-daemon.service ./daemon/griffon-daemon.service

COPY ./daemon/config_griffon_daemon.json ./daemon/config_griffon_daemon.json
COPY ./bench/configs/light.json ./bench/configs/light.json
COPY ./bench/configs/medium.json ./bench/configs/medium.json
COPY ./bench/configs/stress.json ./bench/configs/stress.json

ENTRYPOINT ["sh", "scripts/build-packages.sh"]