tag = false
push = false
publish = false

[[pre-release-replacements]]
file = "nfpm.yaml"
search = 'version: "[0-9a-z\.-]+"'
replace = 'version: "{{version}}"'

[[pre-release-replacements]]
file = "scripts/build.sh"
search = "griffon-[0-9a-z\.-]+\\.deb"
replace = "griffon-{{version}}.deb"

[[pre-release-replacements]]
file = "scripts/build.sh"
search = "griffon-[0-9a-z\.-]+\\.rpm"
replace = "griffon-{{version}}.rpm"
