{
 "title": "example data dashboard",
 "time": { "from": "2000-01-02T00:00:00.000Z", "to": "2000-01-07T00:00:00.000Z" },
 "panels": [
  {
   "title": "performance evolution between version 0.1 and 1.0",
   "type": "xychart",
   "gridPos": { "h": 22, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT ram_usage, cpu_usage, disk_usage, version FROM system_metrics_2 WHERE plugin = 'Scanner' and version = 0.1 or plugin = 'Scanner' and version = 1.0;",
     "rawQueryText": "SELECT ram_usage, cpu_usage, disk_usage, version FROM system_metrics_2 WHERE plugin = 'Scanner' and version = 0.1 or plugin = 'Scanner' and version = 1.0;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "performance evolution of version 0.x",
   "type": "xychart",
   "gridPos": { "h": 22, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT ram_usage, cpu_usage, disk_usage, version, 40 AS threshold FROM system_metrics_2 WHERE plugin = 'Scanner' and version < 1;\n",
     "rawQueryText": "SELECT ram_usage, cpu_usage, disk_usage, version, 40 AS threshold FROM system_metrics_2 WHERE plugin = 'Scanner' and version < 1;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "ram usage of version 0.1",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 4, "x": 13, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT ram_usage, version FROM system_metrics_2 WHERE plugin = 'Scanner' and version = 0.1;\n",
     "rawQueryText": "SELECT ram_usage, version FROM system_metrics_2 WHERE plugin = 'Scanner' and version = 0.1;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}