Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "griffon-cleaner-bench"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.synced_folder "..", "/home/vagrant/GriffonAV"

  config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.name = "griffon-cleaner-bench"
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "scripts/bootstrap.sh"
end