[package]
name = "griffon-daemon"
version.workspace = true
edition = "2024"
default-run = "griffon-daemon"

[dependencies]
plugin_manager = { workspace = true }
ipc_protocol = { workspace = true }
logger = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
uuid = { version = "1.22.0", features = ["v4"] }
nix = { version = "0.30", features = ["fs", "user"] }
notify-rust = "4.17.0"
serde_json = "1.0.150"
